### ISSUE TITLE
Update devnet build to new config

### ISSUE THREAD

**Issue by abelboldu** [LiskHQ/lisk-jenkins#16]
The devnet-build workflow uses the config and versioning of pre 1.1.0 .

We need to update them to use new network parameter (if needed) and version in lisk build steps.

**Comment by ghost** [comment]
AFAICT we only need to change the one line:
https://github.com/LiskHQ/lisk-jenkins/blob/0.1.0/workflows/devnet-build/Jenkinsfile#L41
